let nids={act:100,prest:20,mant:10,epp:10,sol:10,asis:20,w:10,u:10,cmov:10,sima:10,smov:10,proy:10};

const S={
  user:null,
  workers:[
    {id:1,nombre:'Alcántara Sanchez, Alex Gino',apellidos:'Alcántara Sanchez',nombres:'Alex Gino',dni:'32979703',username:'alcantaraa2',cargo:'',esp:'',contrato:'Por hora',tarifa:15,email:'',tel:'',ingreso:'',cumple:'',estado:'Activo',nivel:'Lectura',apodos:['pelao']},
    {id:2,nombre:'Alva Loyola, Jose Manuel',apellidos:'Alva Loyola',nombres:'Jose Manuel',dni:'32779380',username:'alvaj3',cargo:'',esp:'',contrato:'Por hora',tarifa:15,email:'',tel:'',ingreso:'',cumple:'',estado:'Activo',nivel:'Lectura',apodos:[]},
    {id:3,nombre:'Alva Olivares, Juan Carlos',apellidos:'Alva Olivares',nombres:'Juan Carlos',dni:'45328863',username:'alvaj',cargo:'',esp:'',contrato:'Por hora',tarifa:15,email:'',tel:'',ingreso:'',cumple:'',estado:'Activo',nivel:'Lectura',apodos:[]},
    {id:4,nombre:'Anampa Campos, Carlos Alexis',apellidos:'Anampa Campos',nombres:'Carlos Alexis',dni:'77893640',username:'anampac2',cargo:'',esp:'',contrato:'Por hora',tarifa:15,email:'',tel:'',ingreso:'',cumple:'',estado:'Activo',nivel:'Lectura',apodos:[]},
    {id:5,nombre:'Calderón Herrera, Carlos Enrique',apellidos:'Calderón Herrera',nombres:'Carlos Enrique',dni:'40067038',username:'calderonc2',cargo:'',esp:'',contrato:'Por hora',tarifa:15,email:'',tel:'',ingreso:'',cumple:'',estado:'Activo',nivel:'Lectura',apodos:['chato']},
    {id:6,nombre:'Calderon Rojas, Augusto Cesar',apellidos:'Calderon Rojas',nombres:'Augusto Cesar',dni:'09541503',username:'calderona2',cargo:'',esp:'',contrato:'Por hora',tarifa:15,email:'',tel:'',ingreso:'',cumple:'',estado:'Activo',nivel:'Lectura',apodos:[]},
    {id:7,nombre:'Cardenas Cardenas, Jose Luis',apellidos:'Cardenas Cardenas',nombres:'Jose Luis',dni:'41516280',username:'cardenasj2',cargo:'',esp:'',contrato:'Por hora',tarifa:15,email:'',tel:'',ingreso:'',cumple:'',estado:'Activo',nivel:'Lectura',apodos:[]},
    {id:8,nombre:'Cari Alvarez, Gabino Julian',apellidos:'Cari Alvarez',nombres:'Gabino Julian',dni:'29512116',username:'carig2',cargo:'',esp:'',contrato:'Por hora',tarifa:15,email:'',tel:'',ingreso:'',cumple:'',estado:'Activo',nivel:'Lectura',apodos:[]},
    {id:9,nombre:'Castillo Custodio, Edward Manuel',apellidos:'Castillo Custodio',nombres:'Edward Manuel',dni:'74212989',username:'castilloe2',cargo:'',esp:'',contrato:'Por hora',tarifa:15,email:'',tel:'',ingreso:'',cumple:'',estado:'Activo',nivel:'Lectura',apodos:['harry']},
    {id:10,nombre:'Castillo Esquivel, David Armando',apellidos:'Castillo Esquivel',nombres:'David Armando',dni:'70204333',username:'castillod3',cargo:'',esp:'',contrato:'Por hora',tarifa:15,email:'',tel:'',ingreso:'',cumple:'',estado:'Activo',nivel:'Lectura',apodos:['burrito']},
    {id:11,nombre:'Castillo Haro, Javier Armando',apellidos:'Castillo Haro',nombres:'Javier Armando',dni:'32989195',username:'castilloj2',cargo:'',esp:'',contrato:'Por hora',tarifa:15,email:'',tel:'',ingreso:'',cumple:'',estado:'Activo',nivel:'Lectura',apodos:['zombie']},
    {id:12,nombre:'Castillo Landauro, Ricardo Manuel',apellidos:'Castillo Landauro',nombres:'Ricardo Manuel',dni:'32785706',username:'castillor2',cargo:'',esp:'',contrato:'Por hora',tarifa:15,email:'',tel:'',ingreso:'',cumple:'',estado:'Activo',nivel:'Lectura',apodos:[]},
    {id:13,nombre:'Castillo Ruiz, Kevin Yarmain',apellidos:'Castillo Ruiz',nombres:'Kevin Yarmain',dni:'75213359',username:'castillok2',cargo:'',esp:'',contrato:'Por hora',tarifa:15,email:'',tel:'',ingreso:'',cumple:'',estado:'Activo',nivel:'Lectura',apodos:[]},
    {id:14,nombre:'Castillo Ruiz, Diego Alexander',apellidos:'Castillo Ruiz',nombres:'Diego Alexander',dni:'75213359',username:'castillod',cargo:'',esp:'',contrato:'Por hora',tarifa:15,email:'',tel:'',ingreso:'',cumple:'',estado:'Activo',nivel:'Lectura',apodos:[]},
    {id:15,nombre:'Chauca Aguirre, Eduardo Cesar',apellidos:'Chauca Aguirre',nombres:'Eduardo Cesar',dni:'75916180',username:'chaucae2',cargo:'',esp:'',contrato:'Por hora',tarifa:15,email:'',tel:'',ingreso:'',cumple:'',estado:'Activo',nivel:'Lectura',apodos:[]},
    {id:16,nombre:'Chauca de la Cruz, Manuel Arturo',apellidos:'Chauca de la Cruz',nombres:'Manuel Arturo',dni:'43388643',username:'chaucam2',cargo:'',esp:'',contrato:'Por hora',tarifa:15,email:'',tel:'',ingreso:'',cumple:'',estado:'Activo',nivel:'Lectura',apodos:[]},
    {id:17,nombre:'Chiroque Gonzales, Luis Glaber',apellidos:'Chiroque Gonzales',nombres:'Luis Glaber',dni:'41846983',username:'chiroquel2',cargo:'',esp:'',contrato:'Por hora',tarifa:15,email:'',tel:'',ingreso:'',cumple:'',estado:'Activo',nivel:'Lectura',apodos:[]},
    {id:18,nombre:'Cortez Sanchez, Jeanpier',apellidos:'Cortez Sanchez',nombres:'Jeanpier',dni:'75474713',username:'cortezj2',cargo:'',esp:'',contrato:'Por hora',tarifa:15,email:'',tel:'',ingreso:'',cumple:'',estado:'Activo',nivel:'Lectura',apodos:[]},
    {id:19,nombre:'Cribillero Cribillero, Larry Ivan',apellidos:'Cribillero Cribillero',nombres:'Larry Ivan',dni:'43240795',username:'cribillerol2',cargo:'',esp:'',contrato:'Por hora',tarifa:15,email:'',tel:'',ingreso:'',cumple:'',estado:'Activo',nivel:'Lectura',apodos:[]},
    {id:20,nombre:'Cueva Cortez, Jimmy Jhon',apellidos:'Cueva Cortez',nombres:'Jimmy Jhon',dni:'40836880',username:'cuevaj2',cargo:'',esp:'',contrato:'Por hora',tarifa:15,email:'',tel:'',ingreso:'',cumple:'',estado:'Activo',nivel:'Lectura',apodos:[]},
    {id:21,nombre:'Felipe Julca, Jasler Andres',apellidos:'Felipe Julca',nombres:'Jasler Andres',dni:'47343741',username:'felipej2',cargo:'',esp:'',contrato:'Por hora',tarifa:15,email:'',tel:'',ingreso:'',cumple:'',estado:'Activo',nivel:'Lectura',apodos:[]},
    {id:22,nombre:'Flores Chire, Eduardo Luis',apellidos:'Flores Chire',nombres:'Eduardo Luis',dni:'46806411',username:'florese2',cargo:'',esp:'',contrato:'Por hora',tarifa:15,email:'',tel:'',ingreso:'',cumple:'',estado:'Activo',nivel:'Lectura',apodos:[]},
    {id:23,nombre:'Gil Quezada, Jhan Carlos',apellidos:'Gil Quezada',nombres:'Jhan Carlos',dni:'73778948',username:'gilj2',cargo:'',esp:'',contrato:'Por hora',tarifa:15,email:'',tel:'',ingreso:'',cumple:'',estado:'Activo',nivel:'Lectura',apodos:[]},
    {id:143,nombre:'Hidalgo Aguinda, Luis',apellidos:'Hidalgo Aguinda',nombres:'Luis',dni:'46578614',username:'hidalgol2',cargo:'',esp:'',contrato:'Por hora',tarifa:15,email:'',tel:'',ingreso:'',cumple:'',estado:'Activo',nivel:'Lectura',apodos:[]},
    {id:24,nombre:'Huayambaho Rodriguez, Jorge Luis',apellidos:'Huayambaho Rodriguez',nombres:'Jorge Luis',dni:'05957366',username:'huayambahoj2',cargo:'',esp:'',contrato:'Por hora',tarifa:15,email:'',tel:'',ingreso:'',cumple:'',estado:'Activo',nivel:'Lectura',apodos:[]},
    {id:25,nombre:'Limay Valderrama, Marco Antonio',apellidos:'Limay Valderrama',nombres:'Marco Antonio',dni:'45240185',username:'limaym2',cargo:'',esp:'',contrato:'Por hora',tarifa:15,email:'',tel:'',ingreso:'',cumple:'',estado:'Activo',nivel:'Lectura',apodos:[]},
    {id:26,nombre:'Mauricio Lopez, Stiven Charle',apellidos:'Mauricio Lopez',nombres:'Stiven Charle',dni:'43458572',username:'mauricios2',cargo:'',esp:'',contrato:'Por hora',tarifa:15,email:'',tel:'',ingreso:'',cumple:'',estado:'Activo',nivel:'Lectura',apodos:['tito']},
    {id:27,nombre:'Maza Chiroque, Alexis Rivaldo',apellidos:'Maza Chiroque',nombres:'Alexis Rivaldo',dni:'72257401',username:'mazaa2',cargo:'',esp:'',contrato:'Por hora',tarifa:15,email:'',tel:'',ingreso:'',cumple:'',estado:'Activo',nivel:'Lectura',apodos:[]},
    {id:28,nombre:'Mendoza Huamani, Víctor Wilmer',apellidos:'Mendoza Huamani',nombres:'Víctor Wilmer',dni:'40340842',username:'mendozav2',cargo:'',esp:'',contrato:'Por hora',tarifa:15,email:'',tel:'',ingreso:'',cumple:'',estado:'Activo',nivel:'Lectura',apodos:[]},
    {id:29,nombre:'Mogollón Osorio, Leer Joel',apellidos:'Mogollón Osorio',nombres:'Leer Joel',dni:'42565706',username:'mogollonl2',cargo:'',esp:'',contrato:'Por hora',tarifa:15,email:'',tel:'',ingreso:'',cumple:'',estado:'Activo',nivel:'Lectura',apodos:[]},
    {id:30,nombre:'Moreno Pasquel, William Alexander',apellidos:'Moreno Pasquel',nombres:'William Alexander',dni:'46704127',username:'morenow2',cargo:'',esp:'',contrato:'Por hora',tarifa:15,email:'',tel:'',ingreso:'',cumple:'',estado:'Activo',nivel:'Lectura',apodos:[]},
    {id:31,nombre:'Oneglio Majino, Jaimes Yemin',apellidos:'Oneglio Majino',nombres:'Jaimes Yemin',dni:'41461664',username:'oneglioj2',cargo:'',esp:'',contrato:'Por hora',tarifa:15,email:'',tel:'',ingreso:'',cumple:'',estado:'Activo',nivel:'Lectura',apodos:[]},
    {id:32,nombre:'Orbegozo Gamarra, Luis Oswaldo',apellidos:'Orbegozo Gamarra',nombres:'Luis Oswaldo',dni:'44223465',username:'orbegozol2',cargo:'',esp:'',contrato:'Por hora',tarifa:15,email:'',tel:'',ingreso:'',cumple:'',estado:'Activo',nivel:'Lectura',apodos:[]},
    {id:33,nombre:'Palacios Medina, Jose Martin',apellidos:'Palacios Medina',nombres:'Jose Martin',dni:'32953216',username:'palaciosj2',cargo:'',esp:'',contrato:'Por hora',tarifa:15,email:'',tel:'',ingreso:'',cumple:'',estado:'Activo',nivel:'Lectura',apodos:[]},
    {id:34,nombre:'Quevedo Neyra, Joham Miguel',apellidos:'Quevedo Neyra',nombres:'Joham Miguel',dni:'71047945',username:'quevedoj2',cargo:'',esp:'',contrato:'Por hora',tarifa:15,email:'',tel:'',ingreso:'',cumple:'',estado:'Activo',nivel:'Lectura',apodos:[]},
    {id:35,nombre:'Rengifo Flores, Roberto',apellidos:'Rengifo Flores',nombres:'Roberto',dni:'40163610',username:'rengifor2',cargo:'',esp:'',contrato:'Por hora',tarifa:15,email:'',tel:'',ingreso:'',cumple:'',estado:'Activo',nivel:'Lectura',apodos:[]},
    {id:36,nombre:'Reyes Moreno, Orlando Ismael',apellidos:'Reyes Moreno',nombres:'Orlando Ismael',dni:'70129684',username:'reyeso2',cargo:'',esp:'',contrato:'Por hora',tarifa:15,email:'',tel:'',ingreso:'',cumple:'',estado:'Activo',nivel:'Lectura',apodos:['bacteria']},
    {id:37,nombre:'Rosales Melon, Luis Alberto',apellidos:'Rosales Melon',nombres:'Luis Alberto',dni:'45424380',username:'rosalesl2',cargo:'',esp:'',contrato:'Por hora',tarifa:15,email:'',tel:'',ingreso:'',cumple:'',estado:'Activo',nivel:'Lectura',apodos:[]},
    {id:38,nombre:'Sánchez Burgos, Carlos',apellidos:'Sánchez Burgos',nombres:'Carlos',dni:'43774728',username:'sanchezc2',cargo:'',esp:'',contrato:'Por hora',tarifa:15,email:'',tel:'',ingreso:'',cumple:'',estado:'Activo',nivel:'Lectura',apodos:[]},
    {id:39,nombre:'Silva Agreda, Edilberto Nicolas',apellidos:'Silva Agreda',nombres:'Edilberto Nicolas',dni:'32859652',username:'silvae2',cargo:'',esp:'',contrato:'Por hora',tarifa:15,email:'',tel:'',ingreso:'',cumple:'',estado:'Activo',nivel:'Lectura',apodos:['peluche']},
    {id:40,nombre:'Simpalo Baca, Junnior Aldair',apellidos:'Simpalo Baca',nombres:'Junnior Aldair',dni:'72573958',username:'simpaloj2',cargo:'',esp:'',contrato:'Por hora',tarifa:15,email:'',tel:'',ingreso:'',cumple:'',estado:'Activo',nivel:'Lectura',apodos:[]},
    {id:41,nombre:'Soria Maldonado, Fredy',apellidos:'Soria Maldonado',nombres:'Fredy',dni:'45641024',username:'soriaf2',cargo:'',esp:'',contrato:'Por hora',tarifa:15,email:'',tel:'',ingreso:'',cumple:'',estado:'Activo',nivel:'Lectura',apodos:[]},
    {id:42,nombre:'Tapullima Pereira, Mario',apellidos:'Tapullima Pereira',nombres:'Mario',dni:'43526237',username:'tapullimam2',cargo:'',esp:'',contrato:'Por hora',tarifa:15,email:'',tel:'',ingreso:'',cumple:'',estado:'Activo',nivel:'Lectura',apodos:[]}
  ],
  users:[
    {id:0,nombre:'Admin',email:'admin@serving.pe',pass:'admin1234',nivel:'Admin',estado:'Activo',wid:null,username:'admin'},
    {id:99,nombre:'Almacenero',email:'almacen@serving.pe',pass:'almacen1234',nivel:'Estandar',estado:'Activo',wid:null,username:'almacen'},
    {id:101,nombre:'Alcántara Sanchez, Alex Gino',username:'alcantaraa2',pass:'32979703',nivel:'Lectura',apodos:[],estado:'Activo',wid:1},
    {id:102,nombre:'Alva Loyola, Jose Manuel',username:'alvaj3',pass:'32779380',nivel:'Lectura',apodos:[],estado:'Activo',wid:2},
    {id:103,nombre:'Alva Olivares, Juan Carlos',username:'alvaj',pass:'45328863',nivel:'Lectura',apodos:[],estado:'Activo',wid:3},
    {id:104,nombre:'Anampa Campos, Carlos Alexis',username:'anampac2',pass:'77893640',nivel:'Lectura',apodos:[],estado:'Activo',wid:4},
    {id:105,nombre:'Calderón Herrera, Carlos Enrique',username:'calderonc2',pass:'40067038',nivel:'Lectura',apodos:[],estado:'Activo',wid:5},
    {id:106,nombre:'Calderon Rojas, Augusto Cesar',username:'calderona2',pass:'09541503',nivel:'Lectura',apodos:[],estado:'Activo',wid:6},
    {id:107,nombre:'Cardenas Cardenas, Jose Luis',username:'cardenasj2',pass:'41516280',nivel:'Lectura',apodos:[],estado:'Activo',wid:7},
    {id:108,nombre:'Cari Alvarez, Gabino Julian',username:'carig2',pass:'29512116',nivel:'Lectura',apodos:[],estado:'Activo',wid:8},
    {id:109,nombre:'Castillo Custodio, Edward Manuel',username:'castilloe2',pass:'74212989',nivel:'Lectura',apodos:[],estado:'Activo',wid:9},
    {id:110,nombre:'Castillo Esquivel, David Armando',username:'castillod3',pass:'70204333',nivel:'Lectura',apodos:[],estado:'Activo',wid:10},
    {id:111,nombre:'Castillo Haro, Javier Armando',username:'castilloj2',pass:'32989195',nivel:'Lectura',apodos:[],estado:'Activo',wid:11},
    {id:112,nombre:'Castillo Landauro, Ricardo Manuel',username:'castillor2',pass:'32785706',nivel:'Lectura',apodos:[],estado:'Activo',wid:12},
    {id:113,nombre:'Castillo Ruiz, Kevin Yarmain',username:'castillok2',pass:'75213359',nivel:'Lectura',apodos:[],estado:'Activo',wid:13},
    {id:114,nombre:'Castillo Ruiz, Diego Alexander',username:'castillod',pass:'75213359',nivel:'Lectura',apodos:[],estado:'Activo',wid:14},
    {id:115,nombre:'Chauca Aguirre, Eduardo Cesar',username:'chaucae2',pass:'75916180',nivel:'Lectura',apodos:[],estado:'Activo',wid:15},
    {id:116,nombre:'Chauca de la Cruz, Manuel Arturo',username:'chaucam2',pass:'43388643',nivel:'Lectura',apodos:[],estado:'Activo',wid:16},
    {id:117,nombre:'Chiroque Gonzales, Luis Glaber',username:'chiroquel2',pass:'41846983',nivel:'Lectura',apodos:[],estado:'Activo',wid:17},
    {id:118,nombre:'Cortez Sanchez, Jeanpier',username:'cortezj2',pass:'75474713',nivel:'Lectura',apodos:[],estado:'Activo',wid:18},
    {id:119,nombre:'Cribillero Cribillero, Larry Ivan',username:'cribillerol2',pass:'43240795',nivel:'Lectura',apodos:[],estado:'Activo',wid:19},
    {id:120,nombre:'Cueva Cortez, Jimmy Jhon',username:'cuevaj2',pass:'40836880',nivel:'Lectura',apodos:[],estado:'Activo',wid:20},
    {id:121,nombre:'Felipe Julca, Jasler Andres',username:'felipej2',pass:'47343741',nivel:'Lectura',apodos:[],estado:'Activo',wid:21},
    {id:122,nombre:'Flores Chire, Eduardo Luis',username:'florese2',pass:'46806411',nivel:'Lectura',apodos:[],estado:'Activo',wid:22},
    {id:123,nombre:'Gil Quezada, Jhan Carlos',username:'gilj2',pass:'73778948',nivel:'Lectura',apodos:[],estado:'Activo',wid:23},
    {id:124,nombre:'Huayambaho Rodriguez, Jorge Luis',username:'huayambahoj2',pass:'05957366',nivel:'Lectura',apodos:[],estado:'Activo',wid:24},
    {id:125,nombre:'Limay Valderrama, Marco Antonio',username:'limaym2',pass:'45240185',nivel:'Lectura',apodos:[],estado:'Activo',wid:25},
    {id:126,nombre:'Mauricio Lopez, Stiven Charle',username:'mauricios2',pass:'43458572',nivel:'Lectura',apodos:[],estado:'Activo',wid:26},
    {id:127,nombre:'Maza Chiroque, Alexis Rivaldo',username:'mazaa2',pass:'72257401',nivel:'Lectura',apodos:[],estado:'Activo',wid:27},
    {id:128,nombre:'Mendoza Huamani, Víctor Wilmer',username:'mendozav2',pass:'40340842',nivel:'Lectura',apodos:[],estado:'Activo',wid:28},
    {id:129,nombre:'Mogollón Osorio, Leer Joel',username:'mogollonl2',pass:'42565706',nivel:'Lectura',apodos:[],estado:'Activo',wid:29},
    {id:130,nombre:'Moreno Pasquel, William Alexander',username:'morenow2',pass:'46704127',nivel:'Admin',estado:'Activo',wid:30},
    {id:131,nombre:'Oneglio Majino, Jaimes Yemin',username:'oneglioj2',pass:'41461664',nivel:'Lectura',apodos:[],estado:'Activo',wid:31},
    {id:132,nombre:'Orbegozo Gamarra, Luis Oswaldo',username:'orbegozol2',pass:'44223465',nivel:'Lectura',apodos:[],estado:'Activo',wid:32},
    {id:133,nombre:'Palacios Medina, Jose Martin',username:'palaciosj2',pass:'32953216',nivel:'Lectura',apodos:[],estado:'Activo',wid:33},
    {id:134,nombre:'Quevedo Neyra, Joham Miguel',username:'quevedoj2',pass:'71047945',nivel:'Lectura',apodos:[],estado:'Activo',wid:34},
    {id:135,nombre:'Rengifo Flores, Roberto',username:'rengifor2',pass:'40163610',nivel:'Lectura',apodos:[],estado:'Activo',wid:35},
    {id:136,nombre:'Reyes Moreno, Orlando Ismael',username:'reyeso2',pass:'70129684',nivel:'Lectura',apodos:[],estado:'Activo',wid:36},
    {id:137,nombre:'Rosales Melon, Luis Alberto',username:'rosalesl2',pass:'45424380',nivel:'Lectura',apodos:[],estado:'Activo',wid:37},
    {id:138,nombre:'Sánchez Burgos, Carlos',username:'sanchezc2',pass:'43774728',nivel:'Lectura',apodos:[],estado:'Activo',wid:38},
    {id:139,nombre:'Silva Agreda, Edilberto Nicolas',username:'silvae2',pass:'32859652',nivel:'Lectura',apodos:[],estado:'Activo',wid:39},
    {id:140,nombre:'Simpalo Baca, Junnior Aldair',username:'simpaloj2',pass:'72573958',nivel:'Lectura',apodos:[],estado:'Activo',wid:40},
    {id:141,nombre:'Soria Maldonado, Fredy',username:'soriaf2',pass:'45641024',nivel:'Lectura',apodos:[],estado:'Activo',wid:41},
    {id:243,nombre:'Hidalgo Aguinda, Luis',username:'hidalgol2',pass:'46578614',nivel:'Lectura',estado:'Activo',wid:143},
    {id:142,nombre:'Tapullima Pereira, Mario',username:'tapullimam2',pass:'43526237',nivel:'Lectura',apodos:[],estado:'Activo',wid:42}


  ],
  activos:[
    {id:1,codigo:'MAQ-001',tipo:'maquinaria',cat:'Máquina de soldar MIG',desc:'Soldadora Lincoln Electric MIG 250A',serie:'LIN250-A1',ano:'2021-03-10',valor:4500,mantFrec:'Trimestral',estado:'En préstamo',ubic:'Almacén A - Estante 1',notas:'Voltaje 220V',apodos:[]},
    {id:2,codigo:'MAQ-002',tipo:'maquinaria',cat:'Máquina de soldar TIG',desc:'Soldadora Miller TIG 200 AC/DC',serie:'MIL200-B2',ano:'2022-06-15',valor:6200,mantFrec:'Semestral',estado:'Operativo',ubic:'Almacén A - Estante 1',notas:'Con pedal',apodos:[]},
    {id:3,codigo:'MAQ-003',tipo:'maquinaria',cat:'Máquina de apuntalar',desc:'Apuntaladora hidráulica 20T',serie:'APH-001',ano:'2020-11-20',valor:3200,mantFrec:'Trimestral',estado:'En préstamo',ubic:'Almacén A - Estante 2',notas:'',apodos:[]},
    {id:4,codigo:'MAQ-004',tipo:'maquinaria',cat:'Esmeril pequeño (baby)',desc:'Esmeril angular 4.5" Bosch 750W',serie:'BSCH45',ano:'2023-01-05',valor:280,mantFrec:'Mensual',estado:'Operativo',ubic:'Almacén B - Caja 3',notas:'x5',apodos:[]},
    {id:5,codigo:'MAQ-005',tipo:'maquinaria',cat:'Esmeril grande',desc:'Esmeril angular 9" Makita 2200W',serie:'MAK9-02',ano:'2022-08-10',valor:620,mantFrec:'Mensual',estado:'Mantenimiento',ubic:'Taller',notas:'',apodos:[]},
    {id:6,codigo:'HER-001',tipo:'herramienta',cat:'Manguera',desc:'Manguera acetileno 10m',serie:'MAN-AC',qty:4,disponible:3,ubic:'Almacén B',estado:'Operativo',apodos:[]},
    {id:7,codigo:'HER-002',tipo:'herramienta',cat:'Boquilla acetileno',desc:'Boquilla acetileno N°3 Messer',serie:'BOQ-N3',qty:8,disponible:8,ubic:'Almacén B - Caja 1',estado:'Operativo',apodos:[]},
    {id:8,codigo:'HER-003',tipo:'herramienta',cat:'Regla/Nivel',desc:'Regla acero inox 2m',serie:'REG2M',qty:3,disponible:3,ubic:'Almacén B - Estante 4',estado:'Operativo',apodos:[]},
    {id:9,codigo:'EPP-001',tipo:'epp-s',tipoepp:'Casco de seguridad',stock:12,min:5,prov:'3M Perú',estado:'OK',apodos:[]},
    {id:10,codigo:'EPP-002',tipo:'epp-s',tipoepp:'Botas de punta de acero',stock:3,min:5,prov:'Segusa',estado:'Stock bajo',apodos:[]},
    {id:11,codigo:'CONS-001',tipo:'consumible',cat:'Electrodos',desc:'Electrodo E7018 3.2mm Soldex',unidad:'kg',stock:48,min:10,prov:'Soldex',precio:12.5,apodos:[]},
    {id:12,codigo:'CONS-002',tipo:'consumible',cat:'Discos de corte',desc:'Disco corte 4.5" x 1mm Bosch',unidad:'caja',stock:7,min:3,prov:'Bosch',precio:45,apodos:[]},
    {id:13,codigo:'CONS-003',tipo:'consumible',cat:'Gas',desc:'Argón 99.9%',unidad:'litro',stock:180,min:50,prov:'AGA',precio:0.8,apodos:[]},
    {id:14,codigo:'CONS-004',tipo:'consumible',cat:'Discos de desbaste',desc:'Disco desbaste 7" Norton',unidad:'unidad',stock:2,min:5,prov:'Norton',precio:8.5,apodos:[]},
  ],
  piezasSIMA:[
    {id:1,codigo:'SIMA-001',desc:'Plancha acero naval 10mm 2x1m',modulo:'BALOG 1 - Módulo Popa',cat:'Planchas/Perfiles',qty:20,disponible:15,unidad:'unidad',fecha:'2026-03-10',ubic:'Bahía 3',almac:'Luis García',estado:'En uso',obs:'',apodos:[]},
    {id:2,codigo:'SIMA-002',desc:'Perfil L 4"x4" acero A36',modulo:'BALOG 1 - Estructura',cat:'Planchas/Perfiles',qty:50,disponible:50,unidad:'metro',fecha:'2026-03-12',ubic:'Bahía 3',almac:'Luis García',estado:'En almacén',obs:'',apodos:[]},
    {id:3,codigo:'SIMA-003',desc:'Tubería ASTM A53 6" sch40',modulo:'OPV - Tuberías',cat:'Tuberías',qty:30,disponible:22,unidad:'metro',fecha:'2026-03-14',ubic:'Patio exterior',almac:'Luis García',estado:'En uso',obs:'',apodos:[]},
  ],
  simaMov:[
    {id:1,piezaId:1,accion:'Entrada',qty:20,fecha:'2026-03-10',wid:4,obs:'Recepción inicial SIMA'},
    {id:2,piezaId:1,accion:'Salida',qty:5,fecha:'2026-03-15',wid:1,obs:'Módulo popa sección izq.'},
  ],
  prestamos:[
    {id:1,activoId:1,wid:1,fecha:'2026-03-15 08:30',resp:'Luis García',obs:'Con cable',devuelto:null},
    {id:2,activoId:3,wid:2,fecha:'2026-03-17 09:00',resp:'Luis García',obs:'',devuelto:null},
  ],
  mantenimientos:[
    {id:1,activoId:5,tipo:'Correctivo',fecha:'2026-03-18',tecnico:'Técnico Ramírez',costo:150,estado:'En proceso',desc:'Cambio de escobillas'},
    {id:2,activoId:1,tipo:'Preventivo',fecha:'2026-04-01',tecnico:'Técnico Díaz',costo:80,estado:'Programado',desc:'Revisión trimestral'},
  ],
  epp:[
    {id:1,wid:1,tipo:'Casco de seguridad',talla:'L',resp:'RRHH',fecha:'2026-01-10'},
    {id:2,wid:1,tipo:'Careta de soldar',talla:'Única',resp:'RRHH',fecha:'2026-01-10'},
    {id:3,wid:2,tipo:'Casco de seguridad',talla:'M',resp:'RRHH',fecha:'2026-02-01'},
  ],
  solicitudesEPP:[
    {id:1,wid:3,tipo:'Guantes de cuero',talla:'L',motivo:'Desgaste',urg:'Normal',fecha:'2026-03-17',estado:'Pendiente'},
  ],
  asistencia:[
    {id:1,wid:1,fecha:'2026-03-17',entrada:'08:05',salida:'17:00'},
    {id:2,wid:2,fecha:'2026-03-17',entrada:'07:55',salida:'17:00'},
    {id:3,wid:3,fecha:'2026-03-17',entrada:'08:20',salida:'17:00'},
    {id:4,wid:5,fecha:'2026-03-17',entrada:'08:00',salida:'19:00'},
    {id:5,wid:1,fecha:'2026-03-18',entrada:'08:02',salida:null},
    {id:6,wid:1,fecha:'2026-03-10',entrada:'08:00',salida:'17:00'},
    {id:7,wid:2,fecha:'2026-03-10',entrada:'08:00',salida:'17:00'},
    {id:8,wid:1,fecha:'2026-03-11',entrada:'08:00',salida:'17:00'},
  ],
  consMov:[
    {id:1,activoId:11,tipo:'uso',qty:2,fecha:'2026-03-17',wid:1,obra:'Módulo proa'},
    {id:2,activoId:12,tipo:'uso',qty:1,fecha:'2026-03-17',wid:2,obra:'Sección central'},
  ],
  movimientos:[
    {desc:'Préstamo MAQ-001',accion:'Préstamo',wid:1,hora:'08:30'},
    {desc:'EPP Casco — Jorge',accion:'EPP',wid:3,hora:'09:15'},
    {desc:'CONS-001 -2kg',accion:'Consumo',wid:1,hora:'10:00'},
    {desc:'SIMA-001 entrada 20u',accion:'SIMA',wid:4,hora:'11:00'},
  ],
  proyectos:[
    {id:1,nombre:'BALOG 1',cliente:'Marina de Guerra del Perú',inicio:'2025-06-01',fin:'2027-12-31',pct:35,estado:'En ejecución',desc:'Construcción de módulo de habilitación BALOG 1',fases:[
      {nombre:'Ingeniería y planos',pct:100,estado:'done'},
      {nombre:'Estructuras metálicas',pct:65,estado:'prog'},
      {nombre:'Tuberías y sistemas',pct:20,estado:'prog'},
      {nombre:'Habilitación interior',pct:0,estado:'pend'},
      {nombre:'Pintura y acabados',pct:0,estado:'pend'},
      {nombre:'Pruebas y entrega',pct:0,estado:'pend'},
    ]},
    {id:2,nombre:'BALOG 2',cliente:'Marina de Guerra del Perú',inicio:'2025-09-01',fin:'2028-06-30',pct:10,estado:'En ejecución',desc:'Construcción de módulo BALOG 2',fases:[
      {nombre:'Ingeniería y planos',pct:80,estado:'prog'},
      {nombre:'Estructuras metálicas',pct:5,estado:'prog'},
      {nombre:'Tuberías y sistemas',pct:0,estado:'pend'},
      {nombre:'Habilitación interior',pct:0,estado:'pend'},
      {nombre:'Pintura y acabados',pct:0,estado:'pend'},
    ]},
    {id:3,nombre:'OPV',cliente:'Marina de Guerra del Perú',inicio:'2026-01-15',fin:'2029-03-31',pct:5,estado:'En ejecución',desc:'Módulo OPV — Offshore Patrol Vessel',fases:[
      {nombre:'Ingeniería y diseño',pct:40,estado:'prog'},
      {nombre:'Fabricación módulo proa',pct:0,estado:'pend'},
      {nombre:'Fabricación módulo popa',pct:0,estado:'pend'},
      {nombre:'Integración y pruebas',pct:0,estado:'pend'},
    ]},
  ]
};

